### 宋璐-第3天-Python习题

## Python习题

1. 给定正整数n，编写程序生成以i为键，i*i为值的字典，i为1到n之间的整数（都包括在内）。打印该字典。

> 输入：8
>
> 输出：`{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}`

In [1]:
def solution(n: int):
    dict1 = {}
    ## 作答区域 ↓
    for i in range(1,n+1):
        dict1[i]=i**2
    ## 作答区域 ↑
    #print(dict1)
    return dict1
solution(8)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}

2. 给定正整数n，输出斐波那契数列的前n项，斐波那契数列指的是`1,1,2,3,5,8,13……`
   
> 输入：10
>
> 输出：`1,1,2,3,5,8,13,21,34,55`

In [71]:
def solution(n: int):
    fib = []
    ## 作答区域 ↓
    for i in range(0,n):
        if i==0 or i==1:
            fib.append(1)
        elif i > 1:
            fib.append(fib[i-2]+fib[i-1])  
    #result = ', '.join(map(str, fib))
    #print(result)
    print(*fib, sep=', ')

solution(10)


1, 1, 2, 3, 5, 8, 13, 21, 34, 55


3. 给定正整数n，输出n的因式分解。

> 输入：一个小于1000的正整数，例如90
>
> 输出：`90=2*3*3*5`

In [36]:
def solution(n: int):
    assert 0 < n < 1000
    x=1
    count=1
    ## 作答区域 ↓
    flag = True
    if n == 1:
        return ("Error")
    if n >=1 :
        print(f"{n}=", end="")
        while n != 1:
            x += 1
            if n % x == 0:
                n /= x
                if flag:
                    flag = False
                    print(x, end="")
                    x=1

                else:
                    print(f"*{x}",end="")
                    count+=1
                    x=1
            if x==n and count==1:
                print("*1",end="")
    
    return (count)
solution(99)

99=3*3*11

3

In [2]:
def solution(n: int):
    assert 0 < n < 1000
    yinshu=[]

     
solution(90)

4. 给定一个只包含字符串的数组strs，编写函数`rev_strs(strs)`，逆序输出这个数组，同时字符串也反转。
   
> 输入：`strs = ['abc', 'apple', 'pen']`
> 
> 输出：`['nep', 'elppa', 'cba']`

In [41]:
def rev_strs(strs: list[str]) -> list[str]:
    strs1 = []
    count=0
    ## 作答区域 ↓
    for i in strs:
        strs1.append(i[::-1])
    ## 作答区域 ↑
    return strs1[::-1]

strs = ['abc', 'apple', 'pen']
print(rev_strs(strs))

['nep', 'elppa', 'cba']


5. (1) 使用`numpy`创建一个5*5的数组，数组的元素为随机的0~100(左闭右开)的整数值，打印该数组。

   (2) 修改该数组，使小于30的元素设为30，大于70的元素设为70，打印该数组。

> 输入：[无]
> 
> 输出：两个符合题目要求的5*5数组

In [90]:
# 显式循环
import numpy as np
r3 = np.random.randint(0, 100, size=(5, 5))
print(r3)
x=0
for row in r3:
    y=0
    for ele in row:
        if ele > 70:
            r3[x,y]=70
        if ele < 30:
            r3[x,y]=30
        y+=1
    x+=1
print(r3)

[[ 5  8 21 95 11]
 [40 91 10 76  4]
 [55 29 23 41 81]
 [62 92 23  6 81]
 [82 22 71 70 82]]
[[30 30 30 70 30]
 [40 70 30 70 30]
 [55 30 30 41 70]
 [62 70 30 30 70]
 [70 30 70 70 70]]


In [91]:
# Numpy向量化
import numpy as np

r3 = np.random.randint(0, 100, size=(5, 5))
print("原始数组：")
print(r3)

# 使用NumPy向量化操作修改数组
r3 = np.where(r3 < 30, 30, r3)
r3 = np.where(r3 > 70, 70, r3)

print("修改后的数组：")
print(r3)


原始数组：
[[66 39 67 77 83]
 [39 61  5 91 36]
 [48 80 50  1 24]
 [64 32 51 97 93]
 [76 18  5 85 93]]
修改后的数组：
[[66 39 67 70 70]
 [39 61 30 70 36]
 [48 70 50 30 30]
 [64 32 51 70 70]
 [70 30 30 70 70]]


In [26]:
import numpy as np
# 创建由0到100的数组，以2为步长的数组
r=np.arange(0,100,2,dtype=int)
print(2*"\n",r)
# 创建2行2列的随机数组
r1=np.random.rand(2,2)
print(r1)
# 创建0到100的一维数组
r2=np.array(np.arange(0,100),dtype=int)
print(2*"\n",r2)
# 创建0到100的5x5的随机整数数组
r3 = np.random.randint(0, 101, size=(5, 5))
print(2*"\n",r3)




 [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[[0.08288124 0.48479135]
 [0.41552246 0.55275241]]


 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


 [[93 56 75 71 60]
 [34 62 59 14 62]
 [26  2 47 49 39]
 [27 11 46 80 78]
 [90 66 41 95  2]]
[[False False False False False]
 [False False False False False]
 [ True False False False  True]
 [ True False False False False]
 [ True False False  True False]]


In [77]:
# r4=np.array([[False, False, False, False, False],
#        [False, False, False, False, False],
#        [ True, False, False, False,  True],
#        [ True, False, False, False, False],
#        [ True, False, False,  True, False]])
r4=[r3>70][0]
# 将False更改为1
print(r4)
r5 = r4.astype(int)
print(r4.shape)
print(r5)

[[ True False  True  True False]
 [False False False False False]
 [False False False False False]
 [False False False  True  True]
 [ True False False  True False]]
(5, 5)
[[1 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 1 1]
 [1 0 0 1 0]]


In [88]:
import numpy as np
r3 = np.random.randint(0, 100, size=(5, 5))
print(r3)
x=0
for row in r3:
    y=0
    for ele in row:
        if ele > 70:
            r3[x,y]=70
        if ele < 30:
            r3[x,y]=30
        y+=1
    x+=1
print(r3)

[[69 11 43 36 31]
 [84 86 83 13 38]
 [ 3 28 58 28 90]
 [52 53 82 88 14]
 [68 96 87 41 24]]


In [89]:
x=0
for row in r3:
    y=0
    for ele in row:
        if ele > 70:
            r3[x,y]=70
        if ele < 30:
            r3[x,y]=30
        y+=1
    x+=1
print(r3)

[[69 30 43 36 31]
 [70 70 70 30 38]
 [30 30 58 30 70]
 [52 53 70 70 30]
 [68 70 70 41 30]]
